# Generated by Django 2.2.5 on 2019-10-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='details',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
