# Generated by Django 2.2.5 on 2019-10-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20191023_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='job_category',
        ),
    ]
