# Generated by Django 2.2.5 on 2019-10-22 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
