# Generated by Django 2.2.5 on 2019-10-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20191024_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='Status',
            field=models.CharField(choices=[('1', 'active'), ('2', 'inactive'), ('3', 'deleted')], default=2, max_length=11),
        ),
    ]
