# Generated by Django 2.2.5 on 2019-10-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20191024_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='Status',
        ),
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.CharField(default=2, max_length=11),
        ),
    ]
