# Generated by Django 2.2.5 on 2019-10-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20191024_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['status'], 'verbose_name_plural': 'status'},
        ),
    ]
